version: '3'

services:
  api:
    container_name: sami_container
    restart: always
    build: .
    ports:
      - "3333:3333"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongodb_sami
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
